[package]
name = "multi-git"
description = "multi-git."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/multi-git"
documentation = "https://docs.rs/multi-git"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[[bin]]
name = "mgit"
path = "src/main.rs"

[dependencies]
crossterm = "0.17.7"
git2 = "0.13.7"
rayon = "1.3.1"
serde = { version = "1.0.114", features = ["derive"] }
toml = "0.5.6"
globset = "0.4.5"
log = "0.4.11"
fs-err = "2.3.0"
human-panic = "1.0.3"
structopt = "0.3.15"
bstr = "0.2.13"
strsim = "0.10.0"
