[package]
name = "multi-git"
description = "multi-git."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/multi-git"
documentation = "https://docs.rs/multi-git"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"
build = "build.rs"

[[bin]]
name = "mgit"
path = "src/main.rs"

[dependencies]
crossterm = "0.19.0"
git2 = "0.13.19"
rayon = "1.5.1"
serde = { version = "1.0.126", features = ["derive"] }
toml = "0.5.8"
globset = "0.4.6"
log = "0.4.14"
fs-err = "2.6.0"
human-panic = "1.0.3"
structopt = "0.3.21"
bstr = "0.2.16"
strsim = "0.10.0"
num_cpus = "1.13.0"
url = "2.2.2"
toml_edit = { git = "https://github.com/ironyman/toml_edit", branch = "dotted2" }
fn-error-context = "0.1.2"
serde_ignored = "0.1.2"
serde_json = "1.0.64"

[build-dependencies.vergen]
version = "5.1.6"
default-features = false
features = ["git"]

[dev-dependencies]
assert_cmd = "1.0.7"
assert_fs = "1.0.3"
predicates = "2.0.0"
regex = "1.5.4"
shell-words = "1.0.0"
which = "4.1.0"
